<?php
define('API_MODE', true);
ob_start(); // Start buffering
error_reporting(0);
ini_set('display_errors', 0);
header('Content-Type: application/json');
header("Access-Control-Allow-Origin: *");

if (session_status() === PHP_SESSION_NONE) session_start();
include 'db_connect.php';

// Discard any output generated by includes (whitespace, warnings)
ob_clean(); 

if ($conn->connect_error) {
    echo json_encode(['error' => 'Database Connection Failed: ' . $conn->connect_error]);
    exit;
}

if (file_exists('secrets.php')) {
    include 'secrets.php';
} else {
    define('OPENAI_API_KEY', ''); // Fallback or env var
}

$action = $_GET['action'] ?? '';
$role = $_SESSION['role'] ?? '';
$uid = $_SESSION['user_id'] ?? 0;

$allowed_public_actions = ['get_announcements'];

if (!$uid && !in_array($action, $allowed_public_actions)) {
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}

// Admin-only actions
$admin_actions = ['stats', 'recent_users', 'reports', 'admin_programs', 'create_program', 'admin_applications', 'send_material', 'all_citizens', 'manual_enroll', 'delete_program', 'delete_application', 'update_program', 'upload_doc', 'delete_doc', 'approve_edit', 'get_edit_requests', 'toggle_user_status', 'add_calendar_event', 'delete_calendar_event', 'get_calendar_stats', 'fix_account', 'create_announcement', 'delete_announcement', 'get_maintenance', 'sync_maintenance', 'get_analytics'];
if (in_array($action, $admin_actions) && $role !== 'admin') {
     echo json_encode(['error' => 'Unauthorized Access']);
     exit;
}

// Block deactivated users from performing actions (allow getting notifications/basic check)
if ($role === 'user') {
    $resStatus = $conn->query("SELECT is_active FROM users WHERE id = $uid");
    $userStatus = $resStatus->fetch_assoc();
    if (isset($userStatus['is_active']) && $userStatus['is_active'] == 0) {
        $allowed = ['get_notifications', 'mark_read', 'mark_all_read', 'request_reactivation']; // Essential only + reactivation
        if (!in_array($action, $allowed)) {
             echo json_encode(['error' => 'Account Suspended. Please contact administrator.']);
             exit;
        }
    }
}

// Ensure users table has bio column
$conn->query("ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT AFTER interests");
$conn->query("ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_analysis_result TEXT AFTER bio");
$conn->query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255) AFTER email");

// Ensure notifications table exists
$conn->query("CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    title VARCHAR(200),
    message TEXT,
    is_read TINYINT(1) DEFAULT 0,
    type VARCHAR(50) DEFAULT 'info',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)");

// --- USER & SHARED ACTIONS ---

if ($action === 'user_stats') {
    // Stats for specific user
    $stats = [];
    
    // Total Reports
    $stmt = $conn->prepare("SELECT COUNT(*) as c FROM reports WHERE user_id = ?");
    $stmt->bind_param("i", $uid);
    $stmt->execute();
    $stats['total_reports'] = $stmt->get_result()->fetch_assoc()['c'];

    // Pending
    $stmt = $conn->prepare("SELECT COUNT(*) as c FROM reports WHERE user_id = ? AND status = 'pending'");
    $stmt->bind_param("i", $uid);
    $stmt->execute();
    $stats['pending_reports'] = $stmt->get_result()->fetch_assoc()['c'];

    echo json_encode($stats);
    exit;
}

if ($action === 'my_reports') {
    $reports = [];
    
    // Schema Patch: Check correct timestamp column
    $tsCol = 'created_at';
    $check = $conn->query("SHOW COLUMNS FROM reports LIKE 'submitted_at'");
    if($check && $check->num_rows > 0) $tsCol = 'submitted_at';
    
    $stmt = $conn->prepare("SELECT id, title, description, status, $tsCol as created_at FROM reports WHERE user_id = ? ORDER BY $tsCol DESC");
    $stmt->bind_param("i", $uid);
    $stmt->execute();
    $result = $stmt->get_result();
    
    while($row = $result->fetch_assoc()) {
        $reports[] = $row;
    }
    echo json_encode($reports);
    exit;
}


if ($action === 'create_report') {
    $input = json_decode(file_get_contents('php://input'), true);
    $title = $input['title'] ?? '';
    $desc = $input['description'] ?? '';
    
    if(!$title || !$desc) {
        echo json_encode(['error' => 'Missing fields']);
        exit;
    }

    $sql = "INSERT INTO reports (user_id, title, description, status) VALUES (?, ?, ?, 'pending')";
    $stmt = $conn->prepare($sql);

    // Auto-healing: If prepare fails, table might not exist
    if (!$stmt) {
        $createSql = "CREATE TABLE IF NOT EXISTS reports (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT,
            title VARCHAR(200),
            description TEXT,
            status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )";
        $conn->query($createSql);
        
        // Retry
        $stmt = $conn->prepare($sql);
        
        if (!$stmt) {
             // Check if it's a column mismatch (specifically 'description')
             if (strpos($conn->error, "Unknown column 'description'") !== false) {
                 $conn->query("ALTER TABLE reports ADD COLUMN description TEXT AFTER title");
                 $stmt = $conn->prepare($sql); // Retry 2
             }
        }

        if (!$stmt) {
            // Still failing? Return DB error
            echo json_encode(['error' => 'Database Error: ' . $conn->error]);
            exit;
        }
    }

    $stmt->bind_param("iss", $uid, $title, $desc);
    
    if(!$stmt->execute()) {
        // Execute failed, might be column missing if prepare passed (some drivers lazy check)
        if (strpos($stmt->error, "Unknown column 'description'") !== false) {
             $conn->query("ALTER TABLE reports ADD COLUMN description TEXT AFTER title");
             // Re-bind and execute
             if($stmt->execute()) {
                 $reportId = $stmt->insert_id;
                 $success = true;
             }
        }
        if (!$success) {
            echo json_encode(['error' => $stmt->error]);
            exit;
        }
    } else {
        $reportId = $stmt->insert_id;
    }

    // --- NOTIFICATIONS ---
    // 1. Notify User
    $uMsg = "Your report '$title' has been received. Our team will review it shortly.";
    $stmtU = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Report Received', ?, 'info')");
    $stmtU->bind_param("is", $uid, $uMsg);
    $stmtU->execute();

    // 2. Notify All Admins
    $uname = 'A citizen';
    $uRes = $conn->query("SELECT full_name FROM users WHERE id = $uid");
    if($uRes && $uRes->num_rows > 0) $uname = $uRes->fetch_assoc()['full_name'];

    $aMsg = "$uname has submitted a new report: '$title'.";
    $admins = $conn->query("SELECT id FROM users WHERE role = 'admin'");
    while($adm = $admins->fetch_assoc()) {
        $adminId = $adm['id'];
        $stmtA = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'New Report Submitted', ?, 'warning')");
        $stmtA->bind_param("is", $adminId, $aMsg);
        $stmtA->execute();
    }

    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'update_profile') {
    // Handle File Upload
    $response = ['success' => true];
    
    if (isset($_FILES['profile_image']) && $_FILES['profile_image']['error'] == 0) {
        $target_dir = "uploads/";
        if (!file_exists($target_dir)) { mkdir($target_dir, 0777, true); }
        
        $fileName = time() . "_" . basename($_FILES["profile_image"]["name"]);
        $target_file = $target_dir . $fileName;
        
        if (move_uploaded_file($_FILES["profile_image"]["tmp_name"], $target_file)) {
            $stmt = $conn->prepare("UPDATE users SET profile_image = ? WHERE id = ?");
            if ($stmt) {
                $stmt->bind_param("si", $target_file, $uid);
                $stmt->execute();
                $response['image_url'] = $target_file;
            } else {
                $response['error'] = 'DB Prepare Error: ' . $conn->error;
            }
        } else {
            $response['error'] = 'Failed to upload image';
            echo json_encode($response); exit;
        }
    }
    
    // Update Name/Email if provided (optional, simple implementation)
    // For now we just handled the image as per request "can upload image"
    
    echo json_encode($response);
    exit;
}


if ($action === 'submit_assessment') {
    $input = json_decode(file_get_contents('php://input'), true);
    $skills = $input['skills'] ?? '';
    $interests = $input['interests'] ?? '';
    $status = $input['employment_status'] ?? '';
    $bio = $input['bio'] ?? '';
    
    // 1. Save Profile
    $stmt = $conn->prepare("UPDATE users SET skills = ?, interests = ?, employment_status = ?, bio = ? WHERE id = ?");
    $stmt->bind_param("ssssi", $skills, $interests, $status, $bio, $uid);
    $stmt->execute();
    
    // 2. Real-time AI Recommendation Engine (Gemini Powered)
    $programs = [];
    $resProgs = $conn->query("SELECT id, title, category, description FROM programs");
    while($p = $resProgs->fetch_assoc()) $programs[] = $p;
    
    $recommendations = [];
    if (!empty($programs)) {
        $recommendations = analyzeRecommendationsAI($skills, $interests, $programs, $bio);
    }
    
    // Save Result
    $jsonResult = json_encode($recommendations);
    $stmt = $conn->prepare("UPDATE users SET ai_analysis_result = ? WHERE id = ?");
    $stmt->bind_param("si", $jsonResult, $uid);
    $stmt->execute();
    
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'admin_programs') {
    $programs = [];
    $sql = "SELECT * FROM programs ORDER BY created_at DESC";
    $res = $conn->query($sql);
    
    if(!$res) {
        // Auto-heal: Create unique table
        $conn->query("CREATE TABLE IF NOT EXISTS programs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            title VARCHAR(200),
            category VARCHAR(100),
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )");
        $res = $conn->query($sql);
    }
    
    if($res) {
        while($row = $res->fetch_assoc()) {
            $programs[] = $row;
        }
    }
    echo json_encode($programs);
    exit;
}

if ($action === 'create_program') {
    $input = json_decode(file_get_contents('php://input'), true);
    $title = $input['title'] ?? '';
    $cat = $input['category'] ?? '';
    $desc = $input['description'] ?? '';
    
    if(!$title || !$cat) {
        echo json_encode(['error' => 'Title and Category required']);
        exit;
    }
    
    $stmt = $conn->prepare("INSERT INTO programs (title, category, description) VALUES (?, ?, ?)");
    
    // Auto-heal
    if(!$stmt) {
        $conn->query("CREATE TABLE IF NOT EXISTS programs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            title VARCHAR(200),
            category VARCHAR(100),
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )");
        $stmt = $conn->prepare("INSERT INTO programs (title, category, description) VALUES (?, ?, ?)");
    }
    
    if ($stmt) {
        $stmt->bind_param("sss", $title, $cat, $desc);
    } else {
        echo json_encode(['error' => 'Database Error: ' . $conn->error]);
        exit;
    }
    
    if($stmt->execute()) {
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $stmt->error]);
    }
    exit;
}

// --- APPLICATION ACTIONS ---

if ($action === 'apply_program') {
    $input = json_decode(file_get_contents('php://input'), true);
    $progId = $input['program_id'];
    
    // Auto-heal table
    $conn->query("CREATE TABLE IF NOT EXISTS program_applications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        program_id INT,
        status VARCHAR(50) DEFAULT 'pending',
        material_link VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");
    
    // Ensure notifications table exists
    $conn->query("CREATE TABLE IF NOT EXISTS notifications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        title VARCHAR(200),
        message TEXT,
        is_read TINYINT(1) DEFAULT 0,
        type VARCHAR(50) DEFAULT 'info',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");
    
    // Check duplicate
    $check = $conn->query("SELECT id FROM program_applications WHERE user_id = $uid AND program_id = $progId");
    if($check && $check->num_rows > 0) {
        echo json_encode(['error' => 'Already applied']);
        exit;
    }
    
    $stmt = $conn->prepare("INSERT INTO program_applications (user_id, program_id) VALUES (?, ?)");
    $stmt->bind_param("ii", $uid, $progId);
    if($stmt->execute()) {
        // Get program title
        $pRes = $conn->query("SELECT title FROM programs WHERE id = $progId");
        $pTitle = ($pRes && $pRes->num_rows > 0) ? $pRes->fetch_assoc()['title'] : 'Program';

        // 1. Notify User
        $uMsg = "You have successfully applied for '$pTitle'. Please wait for admin approval and materials.";
        $stmtU = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Application Sent', ?, 'info')");
        $stmtU->bind_param("is", $uid, $uMsg);
        $stmtU->execute();

        // 2. Notify All Admins
        $uName = 'A user';
        $uRes = $conn->query("SELECT full_name FROM users WHERE id = $uid");
        if($uRes && $uRes->num_rows > 0) $uName = $uRes->fetch_assoc()['full_name'];

        $aMsg = "$uName has applied for '$pTitle'. Review available in Applications panel.";
        $admins = $conn->query("SELECT id FROM users WHERE role = 'admin'");
        while($adm = $admins->fetch_assoc()) {
            $adminId = $adm['id'];
            $stmtA = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'New Program Application', ?, 'info')");
            $stmtA->bind_param("is", $adminId, $aMsg);
            $stmtA->execute();
        }

        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

// Consolidated get_notifications handled below in line 1064

if ($action === 'mark_read') {
    $input = json_decode(file_get_contents('php://input'), true);
    $notifId = $input['id'];
    $conn->query("UPDATE notifications SET is_read = 1 WHERE id = $notifId AND user_id = $uid");
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'get_my_applications') {
    $apps = [];
    
    // Auto-heal
    $conn->query("CREATE TABLE IF NOT EXISTS program_applications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        program_id INT,
        status VARCHAR(50) DEFAULT 'pending',
        material_link VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");

    // Join with programs to get title
    $sql = "SELECT pa.*, p.title, p.category FROM program_applications pa 
            JOIN programs p ON pa.program_id = p.id 
            WHERE pa.user_id = $uid ORDER BY pa.created_at DESC";
    
    $res = $conn->query($sql);
    if($res) {
        while($row = $res->fetch_assoc()) $apps[] = $row;
    }
    echo json_encode($apps);
    exit;
}

if ($action === 'admin_applications') {
    $apps = [];
    
    // Auto-heal
    $conn->query("CREATE TABLE IF NOT EXISTS program_applications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        program_id INT,
        status VARCHAR(50) DEFAULT 'pending',
        material_link VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");

    $sql = "SELECT pa.*, u.full_name, p.title as program_title FROM program_applications pa
            JOIN users u ON pa.user_id = u.id
            JOIN programs p ON pa.program_id = p.id
            ORDER BY pa.created_at DESC";
    $res = $conn->query($sql);
    if($res) {
        while($row = $res->fetch_assoc()) $apps[] = $row;
    }
    echo json_encode($apps);
    exit;
}

if ($action === 'send_material') {
    $input = json_decode(file_get_contents('php://input'), true);
    $appId = $input['id'];
    $link = "view_material.php?app_id=" . $appId; 
    
    $stmt = $conn->prepare("UPDATE program_applications SET status = 'approved', material_link = ? WHERE id = ?");
    $stmt->bind_param("si", $link, $appId);
    
    if($stmt->execute()) {
        // Send Notification
        $res = $conn->query("SELECT pa.user_id, p.title FROM program_applications pa JOIN programs p ON pa.program_id = p.id WHERE pa.id = $appId");
        if($res && $res->num_rows > 0) {
            $data = $res->fetch_assoc();
            $targetUid = $data['user_id'];
            $pTitle = $data['title'];
            $notifTitle = "Application Approved: $pTitle";
            $notifMsg = "Your application for $pTitle has been approved and the material link is now available on your dashboard.";
            $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, 'success')");
            $stmtNotif->bind_param("iss", $targetUid, $notifTitle, $notifMsg);
            $stmtNotif->execute();
        }
        echo json_encode(['success' => true]);
    }
    else echo json_encode(['error' => $conn->error]);
    exit;
}



if ($action === 'manual_enroll') {
    $input = json_decode(file_get_contents('php://input'), true);
    $uid_target = $input['user_id'];
    $progId = $input['program_id'];
    
    // Check duplicate
    $check = $conn->query("SELECT id FROM program_applications WHERE user_id = $uid_target AND program_id = $progId");
    if($check && $check->num_rows > 0) {
        $appId = $check->fetch_assoc()['id'];
    } else {
        $stmt = $conn->prepare("INSERT INTO program_applications (user_id, program_id) VALUES (?, ?)");
        $stmt->bind_param("ii", $uid_target, $progId);
        $stmt->execute();
        $appId = $stmt->insert_id;
    }
    
    $link = "view_material.php?app_id=" . $appId;
    $stmt = $conn->prepare("UPDATE program_applications SET status = 'approved', material_link = ? WHERE id = ?");
    $stmt->bind_param("si", $link, $appId);
    
    if($stmt->execute()) {
        // Send Notification to User
        $res = $conn->query("SELECT user_id, program_id FROM program_applications WHERE id = $appId");
        $appData = $res->fetch_assoc();
        $targetUid = $appData['user_id'];
        $pId = $appData['program_id'];
        $pTitle = $conn->query("SELECT title FROM programs WHERE id = $pId")->fetch_assoc()['title'];
        
        $notifTitle = "Module Sent: $pTitle";
        $notifMsg = "Admin has sent you the learning materials for $pTitle. Check your dashboard!";
        $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, 'success')");
        $stmtNotif->bind_param("iss", $targetUid, $notifTitle, $notifMsg);
        $stmtNotif->execute();

        echo json_encode(['success' => true]);
    } else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'delete_program') {
    $input = json_decode(file_get_contents('php://input'), true);
    $pid = $input['id'];
    // Optional: Delete applications associated with this program
    $conn->query("DELETE FROM program_applications WHERE program_id = $pid");
    $stmt = $conn->prepare("DELETE FROM programs WHERE id = ?");
    $stmt->bind_param("i", $pid);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'update_program') {
    $input = json_decode(file_get_contents('php://input'), true);
    $pid = $input['id'];
    $title = $input['title'];
    $cat = $input['category'];
    $desc = $input['description'];
    
    $stmt = $conn->prepare("UPDATE programs SET title = ?, category = ?, description = ? WHERE id = ?");
    $stmt->bind_param("sssi", $title, $cat, $desc, $pid);
    
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'upload_doc') {
    if (!isset($_FILES['doc_file'])) {
        echo json_encode(['error' => 'No file uploaded']);
        exit;
    }
    
    $title = $_POST['title'] ?? 'Untitled';
    $cat = $_POST['category'] ?? 'General';
    $file = $_FILES['doc_file'];
    
    $uploadDir = 'uploads/docs/';
    if (!is_dir($uploadDir)) mkdir($uploadDir, 0777, true);
    
    $fileName = time() . '_' . basename($file['name']);
    $targetPath = $uploadDir . $fileName;
    
    if (move_uploaded_file($file['tmp_name'], $targetPath)) {
        $stmt = $conn->prepare("INSERT INTO learning_docs (title, category, file_path) VALUES (?, ?, ?)");
        $stmt->bind_param("sss", $title, $cat, $targetPath);
        if ($stmt->execute()) echo json_encode(['success' => true]);
        else echo json_encode(['error' => $conn->error]);
    } else {
        echo json_encode(['error' => 'Failed to move uploaded file']);
    }
    exit;
}

if ($action === 'get_docs') {
    // Auto-heal
    $conn->query("CREATE TABLE IF NOT EXISTS learning_docs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(200),
        category VARCHAR(100),
        file_path VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");
    
    $docs = [];
    $res = $conn->query("SELECT * FROM learning_docs ORDER BY created_at DESC");
    while($row = $res->fetch_assoc()) $docs[] = $row;
    echo json_encode($docs);
    exit;
}

if ($action === 'delete_doc') {
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'];
    
    // Get path to delete file
    $res = $conn->query("SELECT file_path FROM learning_docs WHERE id = $id");
    if ($row = $res->fetch_assoc()) {
        if (file_exists($row['file_path'])) unlink($row['file_path']);
    }
    
    $conn->query("DELETE FROM learning_docs WHERE id = $id");
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'delete_application') {
    $input = json_decode(file_get_contents('php://input'), true);
    $aid = $input['id'];
    $stmt = $conn->prepare("DELETE FROM program_applications WHERE id = ?");
    $stmt->bind_param("i", $aid);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'submitted_programs') { // Renaming reports to programs context in user dash? No, let's keep separate.
    // Create new action for fetching recommendations
}

if ($action === 'get_recommendations') {
    $res = $conn->query("SELECT ai_analysis_result, skills, interests, bio FROM users WHERE id = $uid");
    $row = $res->fetch_assoc();
    $recs = $row['ai_analysis_result'] ? json_decode($row['ai_analysis_result'], true) : [];
    
    // Logic: If empty or first load, and user has any profile data, force AI analysis
    // Even if data is minimal, AI should suggest something.
    if(empty($recs)) {
         $programs = [];
         $resProgs = $conn->query("SELECT id, title, category, description FROM programs");
         while($p = $resProgs->fetch_assoc()) $programs[] = $p;
         
         if (!empty($programs)) {
             $recs = analyzeRecommendationsAI($row['skills'] ?? '', $row['interests'] ?? '', $programs, $row['bio'] ?? '');
             if (!empty($recs)) {
                $jsonResult = $conn->real_escape_string(json_encode($recs));
                $conn->query("UPDATE users SET ai_analysis_result = '$jsonResult' WHERE id = $uid");
             }
         }
    }
    
    // Final Professional Fallback (if AI service is down or no matches)
    if(empty($recs)) {
         $resProgs = $conn->query("SELECT id, title, category, description, NULL as score FROM programs LIMIT 3");
         while($p = $resProgs->fetch_assoc()) $recs[] = $p;
    }
    
    echo json_encode($recs);
    exit;
}

// End of Admin Actions
if ($action === 'stats') {
    // 1. Total Users (exclude admins maybe? usually yes)
    $resUsers = $conn->query("SELECT COUNT(*) as c FROM users WHERE role = 'user'");
    $totalUsers = $resUsers->fetch_assoc()['c'];

    // 2. Pending Reports
    // Check if table exists first to avoid error if migration not run
    $pendingReports = 0;
    $resCheck = $conn->query("SHOW TABLES LIKE 'reports'");
    if ($resCheck && $resCheck->num_rows > 0) {
        $resRep = $conn->query("SELECT COUNT(*) as c FROM reports WHERE status = 'pending'");
        if($resRep) $pendingReports = $resRep->fetch_assoc()['c'];
    }

    // 3. Active Sessions (Users active in last 30 mins)
    // Needs last_activity column
    $activeSessions = 0;
    $resCheckCol = $conn->query("SHOW COLUMNS FROM users LIKE 'last_activity'");
    if ($resCheckCol && $resCheckCol->num_rows > 0) {
         $resActive = $conn->query("SELECT COUNT(*) as c FROM users WHERE last_activity > DATE_SUB(NOW(), INTERVAL 30 MINUTE)");
         if($resActive) $activeSessions = $resActive->fetch_assoc()['c'];
    }

    echo json_encode([
        'total_users' => $totalUsers,
        'pending_reports' => $pendingReports,
        'active_sessions' => $activeSessions
    ]);
    exit;
}

if ($action === 'chatbot') {
    $input = json_decode(file_get_contents('php://input'), true);
    $question = strtolower($input['message'] ?? '');
    
    // Knowledge Base for Barangay and LGU
    $knowledge = [
        'barangay 175' => "Barangay 175 (Camarin) process usually involves visiting the Barangay Hall located near the Camarin D Market. For clearances, bring a valid ID and proof of residency. They are open Monday to Friday, 8:00 AM to 5:00 PM.",
        'clearance' => "To get a Barangay Clearance, you need to provide a valid ID, a cedula (Community Tax Certificate), and a small fee (usually around 50-100 pesos). The process takes about 15-30 minutes.",
        'business permit' => "For Business Permits in our LGU, you must first obtain a Barangay Business Clearance, followed by a Fire Safety Certificate and Health Permit before applying at the City Hall Business One-Stop Shop.",
        'livelihood' => "Our Livelihood programs include Agriculture training, Technical skills, and small business grants. You can apply for these directly through the 'Programs' section in your dashboard.",
        'report' => "If you have a concern like broken street lights or trash collection, use the 'Create Report' button in your dashboard. Our team will review and address it within 3-5 working days.",
        'hours' => "The Barangay Hall and LGU offices are open from Monday to Friday, 8:00 AM up to 5:00 PM (excluding holidays).",
        'location' => "The main LGU City Hall is located in the city center near the transport terminal. Barangay halls are distributed per district.",
        'contact' => "You can contact the LGU hotline at 8-123-4567 for emergency assistance or email us at support@lgu3.gov.ph."
    ];

    $response = "I'm sorry, I don't have specific details on that yet. However, for most barangay processes, you can visit your local Barangay Hall with a valid ID. Would you like to know about our Livelihood programs instead?";

    // Simple keyword matching
    foreach ($knowledge as $key => $answer) {
        if (strpos($question, $key) !== false) {
            $response = $answer;
            break;
        }
    }

    echo json_encode([
        'response' => $response,
        'timestamp' => date('H:i')
    ]);
    exit;
}

if ($action === 'all_citizens') {
    $users = [];
    $query = "SELECT * FROM users WHERE role = 'user' ORDER BY created_at DESC";
    $result = $conn->query($query);
    
    if (!$result) {
        echo json_encode(['error' => 'Query Failed: ' . $conn->error]);
        exit;
    }
    
    while($row = $result->fetch_assoc()) $users[] = $row;
    echo json_encode($users);
    exit;
}

if ($action === 'recent_users') {
    $users = [];
    $query = "SELECT id, full_name, email, created_at, role, is_active FROM users ORDER BY created_at DESC LIMIT 5";
    $result = $conn->query($query);
    while($row = $result->fetch_assoc()) $users[] = $row;
    echo json_encode($users);
    exit;
}

if ($action === 'update_report_status') {
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'] ?? 0;
    $status = $input['status'] ?? '';
    
    if(!$id || !in_array($status, ['approved', 'rejected'])) {
        echo json_encode(['error' => 'Invalid parameters']);
        exit;
    }

    $stmt = $conn->prepare("UPDATE reports SET status = ? WHERE id = ?");
    $stmt->bind_param("si", $status, $id);
    
    if($stmt->execute()) {
        // Send Notification
        $res = $conn->query("SELECT r.user_id, r.title FROM reports r WHERE r.id = $id");
        if($res && $res->num_rows > 0) {
            $data = $res->fetch_assoc();
            $targetUid = $data['user_id'];
            $rTitle = $data['title'];
            $notifType = ($status === 'approved') ? 'success' : 'warning';
            $notifTitle = "Report Update: $rTitle";
            $notifMsg = "Your report '$rTitle' has been marked as " . strtoupper($status) . " by the administration.";
            $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, ?)");
            $stmtNotif->bind_param("isss", $targetUid, $notifTitle, $notifMsg, $notifType);
            $stmtNotif->execute();
        }
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $stmt->error]);
    }
    exit;
}

if ($action === 'reports') {
    $reports = [];
    $resCheck = $conn->query("SHOW TABLES LIKE 'reports'");
    if ($resCheck->num_rows > 0) {
        
        // Dynamic Timestamp Column Check
        $tsCol = 'created_at';
        $check = $conn->query("SHOW COLUMNS FROM reports LIKE 'submitted_at'");
        if($check && $check->num_rows > 0) $tsCol = 'submitted_at';

        $query = "SELECT r.id, r.title, r.description, r.status, r.$tsCol as created_at, u.full_name 
                  FROM reports r 
                  JOIN users u ON r.user_id = u.id 
                  ORDER BY r.$tsCol DESC LIMIT 10";
        $result = $conn->query($query);
        if (!$result) {
            echo json_encode(['error' => $conn->error]);
            exit;
        }
        while($row = $result->fetch_assoc()) {
            $reports[] = $row;
        }
    }
    echo json_encode($reports);
    exit;
}

if ($action === 'request_edit') {
    // Set flag
    $conn->query("UPDATE users SET requesting_edit = 1 WHERE id = $uid");

    // Get user name
    $uname = 'A user';
    $uRes = $conn->query("SELECT full_name FROM users WHERE id = $uid");
    if ($uRes && $uRes->num_rows > 0) {
        $uname = $uRes->fetch_assoc()['full_name'];
    }
    
    // Find an Admin ID
    $adminId = 1;
    $adminRes = $conn->query("SELECT id FROM users WHERE role = 'admin' LIMIT 1");
    if ($adminRes && $adminRes->num_rows > 0) {
        $adminId = $adminRes->fetch_assoc()['id'];
    }
    
    $msg = "$uname has requested permission to edit their profile name.";
    $stmt = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Direct Name Edit Request', ?, 'warning')");
    
    if ($stmt) {
        $stmt->bind_param("is", $adminId, $msg);
        $stmt->execute();
        echo json_encode(['success' => true, 'message' => 'Request sent to Administrator. Please wait for approval.']);
    } else {
        echo json_encode(['error' => 'Database error: ' . $conn->error]);
    }
    exit;
}

if ($action === 'check_edit_auth') {
    $res = $conn->query("SELECT edit_authorized_until FROM users WHERE id = $uid");
    $row = ($res) ? $res->fetch_assoc() : null;
    
    $authorized = false;
    $remaining = 0;
    
    if ($row && $row['edit_authorized_until']) {
        $expiry = strtotime($row['edit_authorized_until']);
        $now = time();
        if ($expiry > $now) {
            $authorized = true;
            $remaining = $expiry - $now;
        }
    }
    
    echo json_encode(['authorized' => $authorized, 'remaining' => $remaining]);
    exit;
}

if ($action === 'update_name') {
    $input = json_decode(file_get_contents('php://input'), true);
    $newName = $input['full_name'] ?? '';
    
    // Check auth again
    $res = $conn->query("SELECT edit_authorized_until FROM users WHERE id = $uid");
    $row = $res->fetch_assoc();
    if (!$row['edit_authorized_until'] || strtotime($row['edit_authorized_until']) < time()) {
        echo json_encode(['error' => 'Edit period expired or not authorized.']);
        exit;
    }
    
    $stmt = $conn->prepare("UPDATE users SET full_name = ?, edit_authorized_until = NULL WHERE id = ?");
    $stmt->bind_param("si", $newName, $uid);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'approve_edit') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $targetUid = $input['user_id'];
    
    // Clear request flag
    $conn->query("UPDATE users SET requesting_edit = 0 WHERE id = $targetUid");
    
    // Set 25 minutes from now
    $conn->query("UPDATE users SET edit_authorized_until = DATE_ADD(NOW(), INTERVAL 25 MINUTE) WHERE id = $targetUid");
    
    // Notify user
    $msg = "Administrator has approved your name change. You have 25 minutes to update your profile.";
    $stmt = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Edit Approved', ?, 'success')");
    $stmt->bind_param("is", $targetUid, $msg);
    $stmt->execute();
    
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'get_edit_requests') {
    if($role !== 'admin') exit;
    $users = [];
    $res = $conn->query("SELECT id, full_name, email, created_at FROM users WHERE requesting_edit = 1");
    if($res) {
        while($row = $res->fetch_assoc()) $users[] = $row;
    }
    echo json_encode($users);
    exit;
}

if ($action === 'toggle_user_status') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $targetUid = $input['user_id'];
    $newStatus = $input['is_active']; // 1 or 0
    
    $stmt = $conn->prepare("UPDATE users SET is_active = ? WHERE id = ?");
    $stmt->bind_param("ii", $newStatus, $targetUid);
    
    if($stmt->execute()) {
        $statusText = $newStatus ? "Activated" : "Deactivated";
        
        // Notify user if possible (they can see it next time or if session allowed)
        $msg = "Your account has been $statusText by an Administrator.";
        $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Account Update', ?, 'info')");
        $stmtNotif->bind_param("is", $targetUid, $msg);
        $stmtNotif->execute();
        
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

if ($action === 'request_reactivation') {
    $input = json_decode(file_get_contents('php://input'), true);
    $reason = $input['reason'] ?? '';
    $refId = $input['reference_id'] ?? '';
    
    // Find admin to notify
    $adminRes = $conn->query("SELECT id FROM users WHERE role = 'admin' LIMIT 1");
    if($admin = $adminRes->fetch_assoc()) {
        $adminId = $admin['id'];
        $uname = $_SESSION['full_name'];
        $msg = "User $uname (Ref: $refId) has requested account reactivation. Reason: $reason";
        
        $stmt = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Reactivation Request', ?, 'warning')");
        $stmt->bind_param("is", $adminId, $msg);
        $stmt->execute();
    }
    
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'fix_account') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $refId = trim($input['reference_id'] ?? '');
    
    if(!$refId) {
        echo json_encode(['error' => 'Reference ID is required']);
        exit;
    }

    $stmt = $conn->prepare("UPDATE users SET is_active = 1 WHERE reference_id = ?");
    $stmt->bind_param("s", $refId);
    
    if($stmt->execute()) {
        if($stmt->affected_rows > 0) {
            // Find user id to notify them
            $res = $conn->query("SELECT id FROM users WHERE reference_id = '$refId'");
            if($u = $res->fetch_assoc()) {
                $targetUid = $u['id'];
                $msg = "Your account has been reactivated via Reference ID check. Welcome back!";
                $conn->query("INSERT INTO notifications (user_id, title, message, type) VALUES ($targetUid, 'Account Reactivated', '$msg', 'success')");
            }
            echo json_encode(['success' => true, 'message' => 'Account successfully reactivated.']);
        } else {
            echo json_encode(['error' => 'Reference ID not found or already active.']);
        }
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

if ($action === 'get_calendar') {
    $events = [];
    if ($role === 'admin') {
        // Admin sees everything
        $sql = "SELECT e.*, GROUP_CONCAT(u.full_name SEPARATOR ', ') as tagged_names 
                FROM calendar_events e 
                LEFT JOIN event_tags et ON e.id = et.event_id
                LEFT JOIN users u ON et.user_id = u.id
                GROUP BY e.id
                ORDER BY e.event_date ASC, e.event_time ASC";
    } else {
        // User sees events they created OR where they are tagged
        $sql = "SELECT e.*, et.status as user_status 
                FROM calendar_events e 
                LEFT JOIN event_tags et ON e.id = et.event_id
                WHERE e.creator_id = $uid OR et.user_id = $uid
                ORDER BY e.event_date ASC, e.event_time ASC";
    }
    
    $res = $conn->query($sql);
    if($res) {
        while($row = $res->fetch_assoc()) $events[] = $row;
    }
    echo json_encode($events);
    exit;
}

if ($action === 'add_calendar_event') {
    $input = json_decode(file_get_contents('php://input'), true);
    $title = $input['title'];
    $desc = $input['description'] ?? '';
    $date = $input['event_date'];
    $time = $input['event_time'] ?? '09:00:00';
    $type = $input['type'] ?? 'task';
    $target_uids = $input['target_user_ids'] ?? []; // Array of IDs

    $stmt = $conn->prepare("INSERT INTO calendar_events (creator_id, title, description, event_date, event_time, type) VALUES (?, ?, ?, ?, ?, ?)");
    $stmt->bind_param("isssss", $uid, $title, $desc, $date, $time, $type);
    
    if($stmt->execute()) {
        $eventId = $conn->insert_id;
        
        // Tag multiple users
        if(!empty($target_uids)) {
            $notifTitle = "New Calendar Event: $title";
            $notifMsg = "You have been tagged in a new calendar event: $title scheduled for $date at $time.";
            
            foreach($target_uids as $target_uid) {
                if(empty($target_uid)) continue;
                $stmtTag = $conn->prepare("INSERT INTO event_tags (event_id, user_id) VALUES (?, ?)");
                $stmtTag->bind_param("ii", $eventId, $target_uid);
                $stmtTag->execute();

                $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, 'info')");
                $stmtNotif->bind_param("iss", $target_uid, $notifTitle, $notifMsg);
                $stmtNotif->execute();
            }
        }
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

if ($action === 'delete_calendar_event') {
    $input = json_decode(file_get_contents('php://input'), true);
    $eventId = $input['id'];
    
    // Only creator can delete
    $stmt = $conn->prepare("DELETE FROM calendar_events WHERE id = ? AND creator_id = ?");
    $stmt->bind_param("ii", $eventId, $uid);
    
    if($stmt->execute() && $stmt->affected_rows > 0) {
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => 'Delete failed or unauthorized']);
    }
    exit;
}

if ($action === 'respond_to_event') {
    $input = json_decode(file_get_contents('php://input'), true);
    $eventId = $input['id'];
    $newStatus = $input['status']; // 'joined' or 'declined'
    
    // Update status in event_tags
    $stmt = $conn->prepare("UPDATE event_tags SET status = ? WHERE event_id = ? AND user_id = ?");
    $stmt->bind_param("sii", $newStatus, $eventId, $uid);
    
    if($stmt->execute() && $stmt->affected_rows > 0) {
        $q = "SELECT title, creator_id FROM calendar_events WHERE id = $eventId";
        $res = $conn->query($q);
        if($res && $row = $res->fetch_assoc()) {
            $creatorId = $row['creator_id'];
            $title = $row['title'];
            $userName = $_SESSION['full_name'];
            $statusText = ucfirst($newStatus);
            
            $notifTitle = "Event Response: $statusText";
            $notifMsg = "$userName has $newStatus the event: $title";
            
            $stmtNotif = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, 'info')");
            $stmtNotif->bind_param("iss", $creatorId, $notifTitle, $notifMsg);
            $stmtNotif->execute();
        }
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => 'Response failed or unauthorized']);
    }
    exit;
}

if ($action === 'get_calendar_stats') {
    $stats = [];
    $sql = "SELECT status, COUNT(*) as count FROM event_tags GROUP BY status";
    $res = $conn->query($sql);
    while($row = $res->fetch_assoc()) {
        $stats[$row['status']] = (int)$row['count'];
    }
    
    $stats['pending'] = $stats['pending'] ?? 0;
    $stats['joined'] = $stats['joined'] ?? 0;
    $stats['declined'] = $stats['declined'] ?? 0;
    
    $total = $stats['pending'] + $stats['joined'] + $stats['declined'];
    $stats['total'] = $total;
    
    if($total > 0) {
        $stats['join_percentage'] = round(($stats['joined'] / $total) * 100, 1);
        $stats['decline_percentage'] = round(($stats['declined'] / $total) * 100, 1);
    } else {
        $stats['join_percentage'] = 0;
        $stats['decline_percentage'] = 0;
    }
    
    echo json_encode($stats);
    exit;
}

// --- NOTIFICATION ENDPOINTS ---

if ($action === 'get_notifications') {
    $notifications = [];
    $stmt = $conn->prepare("SELECT * FROM notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT 20");
    $stmt->bind_param("i", $uid);
    $stmt->execute();
    $res = $stmt->get_result();
    while($row = $res->fetch_assoc()) {
        $notifications[] = $row;
    }
    echo json_encode($notifications);
    exit;
}

if ($action === 'mark_read') {
    $input = json_decode(file_get_contents('php://input'), true);
    $notifId = $input['id'];
    
    $stmt = $conn->prepare("UPDATE notifications SET is_read = 1 WHERE id = ? AND user_id = ?");
    $stmt->bind_param("ii", $notifId, $uid);
    
    if($stmt->execute()) {
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => 'Failed to mark as read']);
    }
    exit;
}

if ($action === 'mark_all_read') {
    $stmt = $conn->prepare("UPDATE notifications SET is_read = 1 WHERE user_id = ? AND is_read = 0");
    $stmt->bind_param("i", $uid);
    
    if($stmt->execute()) {
        echo json_encode(['success' => true, 'updated' => $stmt->affected_rows]);
    } else {
        echo json_encode(['error' => 'Failed to mark all as read']);
    }
    exit;
}

// --- SKILL TEST ACTIONS ---

if ($action === 'get_skill_tests') {
    $tests = [];
    $res = $conn->query("SELECT * FROM skill_tests ORDER BY created_at DESC");
    while($row = $res->fetch_assoc()) $tests[] = $row;
    echo json_encode($tests);
    exit;
}

if ($action === 'get_skill_progress') {
    // Get progress for ALL tests or specific?
    // User wants "link stage 1-5" context.
    // Let's return joined data: test info + current progress
    $data = [];
    $sql = "SELECT st.*, 
            usp.current_stage, usp.status as user_status, usp.score, usp.completed_at
            FROM skill_tests st
            LEFT JOIN user_skill_progress usp ON st.id = usp.test_id AND usp.user_id = $uid";
    $res = $conn->query($sql);
    while($row = $res->fetch_assoc()) {
        // Get total stages count
        $tid = $row['id'];
        $cRes = $conn->query("SELECT COUNT(*) as c FROM skill_test_stages WHERE test_id = $tid");
        $row['total_stages'] = $cRes->fetch_assoc()['c'];
        $data[] = $row;
    }
    echo json_encode($data);
    exit;
}

if ($action === 'enroll_skill') {
    $input = json_decode(file_get_contents('php://input'), true);
    $tid = $input['test_id'];
    
    // Check if enrolled
    $check = $conn->query("SELECT id FROM user_skill_progress WHERE user_id = $uid AND test_id = $tid");
    if($check->num_rows == 0) {
        $stmt = $conn->prepare("INSERT INTO user_skill_progress (user_id, test_id, current_stage, status, started_at) VALUES (?, ?, 1, 'in_progress', NOW())");
        $stmt->bind_param("ii", $uid, $tid);
        $stmt->execute();
    }
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'get_test_stages') {
    $tid = $_GET['test_id'];
    $stages = [];
    $stmt = $conn->prepare("SELECT * FROM skill_test_stages WHERE test_id = ? ORDER BY stage_number ASC");
    $stmt->bind_param("i", $tid);
    $stmt->execute();
    $res = $stmt->get_result();
    while($row = $res->fetch_assoc()) $stages[] = $row;
    echo json_encode($stages);
    exit;
}

if ($action === 'complete_stage') {
    $input = json_decode(file_get_contents('php://input'), true);
    $tid = $input['test_id'];
    $stageNum = $input['stage_number'];
    
    // Verify progress
    $stmt = $conn->prepare("SELECT current_stage, status FROM user_skill_progress WHERE user_id = ? AND test_id = ?");
    $stmt->bind_param("ii", $uid, $tid);
    $stmt->execute();
    $res = $stmt->get_result();
    if($data = $res->fetch_assoc()) {
        // Only update if we are completing the current stage
        if($data['current_stage'] == $stageNum && $data['status'] !== 'completed') {
            $nextStage = $stageNum + 1;
            
            // Count total stages
            $countRes = $conn->query("SELECT COUNT(*) as c FROM skill_test_stages WHERE test_id = $tid");
            $totalStages = $countRes->fetch_assoc()['c'];
            
            if($stageNum >= $totalStages) {
                // Completed
                $conn->query("UPDATE user_skill_progress SET status = 'completed', completed_at = NOW(), score = 100 WHERE user_id = $uid AND test_id = $tid");
            } else {
                $conn->query("UPDATE user_skill_progress SET current_stage = $nextStage WHERE user_id = $uid AND test_id = $tid");
            }
        }
    }
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'get_skill_analytics') {
    if($role !== 'admin') {
         echo json_encode(['error' => 'Unauthorized']); exit;
    }
    
    $analytics = [
        'total_enrollments' => 0,
        'completed_count' => 0,
        'tests' => []
    ];
    
    // Total Enrollments
    $res = $conn->query("SELECT COUNT(*) as c FROM user_skill_progress");
    $analytics['total_enrollments'] = $res->fetch_assoc()['c'];
    
    // Total Completions
    $res = $conn->query("SELECT COUNT(*) as c FROM user_skill_progress WHERE status = 'completed'");
    $analytics['completed_count'] = $res->fetch_assoc()['c'];
    
    // Data per Test
    // Get all tests
    $resTests = $conn->query("SELECT id, title FROM skill_tests");
    while($test = $resTests->fetch_assoc()) {
        $tid = $test['id'];
        
        // Count enrolled in this test
        $resEnrolled = $conn->query("SELECT COUNT(*) as c FROM user_skill_progress WHERE test_id = $tid");
        $enrolled = $resEnrolled->fetch_assoc()['c'];
        
        // Count completed in this test
        $resCompleted = $conn->query("SELECT COUNT(*) as c FROM user_skill_progress WHERE test_id = $tid AND status = 'completed'");
        $completed = $resCompleted->fetch_assoc()['c'];
        
        // Get recent enrollees
        $users = [];
        $sqlUsers = "SELECT u.full_name, u.email, usp.current_stage, usp.status, usp.started_at 
                     FROM user_skill_progress usp
                     JOIN users u ON usp.user_id = u.id
                     WHERE usp.test_id = $tid
                     ORDER BY usp.started_at DESC LIMIT 5";
        $resUsers = $conn->query($sqlUsers);
        while($u = $resUsers->fetch_assoc()) {
            $users[] = $u;
        }

        $analytics['tests'][] = [
            'title' => $test['title'],
            'enrolled' => $enrolled,
            'completed' => $completed,
            'recent_users' => $users
        ];
    }
    
    echo json_encode($analytics);
    exit;
}

// --- SKILL TEST MANAGEMENT (CRUD) ---

if ($action === 'create_skill_test') {
    if($role !== 'admin') exit;
    
    $title = $_POST['title'] ?? '';
    $desc = $_POST['description'] ?? '';
    $thumb = 'https://via.placeholder.com/600x400?text=Skill+Test'; // Default

    // Handle Image Upload
    if (isset($_FILES['image']) && $_FILES['image']['error'] == 0) {
        $target_dir = "uploads/skill_tests/";
        if (!file_exists($target_dir)) mkdir($target_dir, 0755, true);
        
        $fileExt = strtolower(pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION));
        $allowed = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
        if(in_array($fileExt, $allowed)) {
            $fileName = time() . "_" . uniqid() . "." . $fileExt;
            $target_file = $target_dir . $fileName;
            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                $thumb = $target_file;
            }
        }
    }
    
    $stmt = $conn->prepare("INSERT INTO skill_tests (title, description, thumbnail) VALUES (?, ?, ?)");
    $stmt->bind_param("sss", $title, $desc, $thumb);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'update_skill_test') {
    if($role !== 'admin') exit;
    
    $id = $_POST['id'];
    $title = $_POST['title'];
    $desc = $_POST['description'];
    $thumb = $_POST['existing_thumbnail'] ?? ''; // Keep existing by default

    // Handle New Image Upload
    if (isset($_FILES['image']) && $_FILES['image']['error'] == 0) {
        $target_dir = "uploads/skill_tests/";
        if (!file_exists($target_dir)) mkdir($target_dir, 0755, true);
        
        $fileExt = strtolower(pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION));
        $allowed = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
        if(in_array($fileExt, $allowed)) {
            $fileName = time() . "_" . uniqid() . "." . $fileExt;
            $target_file = $target_dir . $fileName;
            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                $thumb = $target_file;
            }
        }
    }
    
    $stmt = $conn->prepare("UPDATE skill_tests SET title = ?, description = ?, thumbnail = ? WHERE id = ?");
    $stmt->bind_param("sssi", $title, $desc, $thumb, $id);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'delete_skill_test') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'];
    
    $conn->query("DELETE FROM skill_tests WHERE id = $id");
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'add_test_stage') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $tid = $input['test_id'];
    $title = $input['title'];
    $content = $input['content'];
    $video = $input['video_url'];
    
    // Auto-calculate stage number
    $res = $conn->query("SELECT MAX(stage_number) as m FROM skill_test_stages WHERE test_id = $tid");
    $nextNum = ($res->fetch_assoc()['m'] ?? 0) + 1;
    
    $stmt = $conn->prepare("INSERT INTO skill_test_stages (test_id, stage_number, title, content, video_url) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("iisss", $tid, $nextNum, $title, $content, $video);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'update_test_stage') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'];
    $title = $input['title'];
    $content = $input['content'];
    $video = $input['video_url'];
    
    $stmt = $conn->prepare("UPDATE skill_test_stages SET title = ?, content = ?, video_url = ? WHERE id = ?");
    $stmt->bind_param("sssi", $title, $content, $video, $id);
    if($stmt->execute()) echo json_encode(['success' => true]);
    else echo json_encode(['error' => $conn->error]);
    exit;
}

if ($action === 'delete_test_stage') {
    if($role !== 'admin') exit;
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'];
    
    $conn->query("DELETE FROM skill_test_stages WHERE id = $id");
    
    // Potentially reorder stages? Keeping it simple for now. 
    echo json_encode(['success' => true]);
    exit;
}


// --- USER SKILL ACTIONS ---

if ($action === 'get_skill_progress') {
    // Auto-heal table
    $conn->query("CREATE TABLE IF NOT EXISTS user_skill_progress (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        test_id INT,
        current_stage INT DEFAULT 1,
        status ENUM('in_progress', 'completed') DEFAULT 'in_progress',
        started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMP NULL
    )");

    $tests = [];
    $res = $conn->query("SELECT * FROM skill_tests");
    while($t = $res->fetch_assoc()) {
        $tid = $t['id'];
        
        // Get Total Stages
        $resStages = $conn->query("SELECT COUNT(*) as c FROM skill_test_stages WHERE test_id = $tid");
        $t['total_stages'] = $resStages->fetch_assoc()['c'];
        
        // Get User Progress
        $resProg = $conn->query("SELECT current_stage, status FROM user_skill_progress WHERE user_id = $uid AND test_id = $tid");
        if($resProg && $resProg->num_rows > 0) {
            $prog = $resProg->fetch_assoc();
            $t['current_stage'] = (int)$prog['current_stage'];
            $t['user_status'] = $prog['status']; // 'in_progress' or 'completed'
            $t['status'] = $prog['status']; // Alias for frontend list view
        } else {
            $t['current_stage'] = 0; // Not enrolled
            $t['user_status'] = null;
            $t['status'] = null;
        }
        
        $tests[] = $t;
    }
    echo json_encode($tests);
    exit;
}

function analyzeRecommendationsAI($skills, $interests, $programs, $bio = "") {
    if (!defined('OPENAI_API_KEY') || empty(OPENAI_API_KEY)) return [];

    $url = "https://api.openai.com/v1/chat/completions";
    
    $progFormatted = [];
    foreach($programs as $p) {
        $progFormatted[] = [
            'id' => $p['id'],
            'title' => $p['title'],
            'category' => $p['category'],
            'description' => $p['description']
        ];
    }
    $progJson = json_encode($progFormatted);

    $systemPrompt = "You are an expert Career Counselor for a local government livelihood program. Your task is to match a citizen to the TOP 3 most relevant programs based on their profile. You must respond with ONLY a valid JSON array of objects. Each object must have 'id' (integer) and 'score' (integer between 1-100). Do not include any explanations, markdown formatting, or code blocks.";
    
    $userPrompt = "Citizen Profile:\nBio: $bio\nSkills: $skills\nInterests: $interests\n\nAvailable Programs:\n$progJson\n\nTASK: Compare the profile (even if minimal) with the programs. If the user wants to LEARN something (e.g. 'I want to learn English'), prioritize programs that teach that skill. If profile is very empty, infer the best general starter programs. Return TOP 3 matches as JSON array.";

    $data = [
        "model" => "gpt-4o",
        "messages" => [
            ["role" => "system", "content" => $systemPrompt],
            ["role" => "user", "content" => $userPrompt]
        ],
        "temperature" => 0.7
    ];
    
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Content-Type: application/json',
        'Authorization: Bearer ' . OPENAI_API_KEY
    ]);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_TIMEOUT, 20);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    $matchedRecs = [];
    if ($httpCode === 200) {
        $result = json_decode($response, true);
        $content = $result['choices'][0]['message']['content'] ?? '[]';
        
        // Clean potential markdown
        $jsonText = preg_replace('/```json|```/', '', $content);
        $aiMatches = json_decode(trim($jsonText), true);
        
        if (is_array($aiMatches)) {
            foreach($aiMatches as $match) {
                foreach($programs as $p) {
                    if ($p['id'] == $match['id']) {
                        $rawScore = (int)($match['score'] ?? 0);
                        $p['score'] = $rawScore > 0 ? $rawScore / 10 : 8.5; 
                        $matchedRecs[] = $p;
                        break;
                    }
                }
            }
        }
    }
    
    return $matchedRecs;
}

if ($action === 'enroll_skill') {
    $input = json_decode(file_get_contents('php://input'), true);
    $tid = $input['test_id'];
    
    // Check if already enrolled
    $check = $conn->query("SELECT id FROM user_skill_progress WHERE user_id = $uid AND test_id = $tid");
    if($check->num_rows == 0) {
        $stmt = $conn->prepare("INSERT INTO user_skill_progress (user_id, test_id, current_stage, status) VALUES (?, ?, 1, 'in_progress')");
        $stmt->bind_param("ii", $uid, $tid);
        $stmt->execute();
    }
    echo json_encode(['success' => true]);
    exit;
}

if ($action === 'get_test_stages') {
    $tid = $_GET['test_id'];
    $stages = [];
    $res = $conn->query("SELECT * FROM skill_test_stages WHERE test_id = $tid ORDER BY stage_number ASC");
    while($row = $res->fetch_assoc()) $stages[] = $row;
    echo json_encode($stages);
    exit;
}

if ($action === 'complete_stage') {
    $input = json_decode(file_get_contents('php://input'), true);
    $tid = $input['test_id'];
    $stageNum = $input['stage_number'];
    
    // Verify current stage matches (prevent skipping)
    $resP = $conn->query("SELECT current_stage, status FROM user_skill_progress WHERE user_id = $uid AND test_id = $tid");
    $prog = $resP->fetch_assoc();
    
    if($prog['status'] === 'completed') {
        echo json_encode(['success' => true, 'already_completed' => true]);
        exit;
    }
    
    if($stageNum == $prog['current_stage']) {
        // Advance Stage
        $nextStage = $stageNum + 1;
        
        // Check if this was the last stage
        $resCount = $conn->query("SELECT COUNT(*) as c FROM skill_test_stages WHERE test_id = $tid");
        $total = $resCount->fetch_assoc()['c'];
        
        if($stageNum >= $total) {
            // COMPLETED!
            $conn->query("UPDATE user_skill_progress SET status = 'completed', completed_at = NOW() WHERE user_id = $uid AND test_id = $tid");
            
            // 1. Notify User (Badge)
            $testTitleRes = $conn->query("SELECT title FROM skill_tests WHERE id = $tid");
            $testTitle = $testTitleRes->fetch_assoc()['title'];
            
            $uMsg = "Congratulations! You have successfully completed the '$testTitle' skill test. A badge has been added to your profile.";
            $stmtU = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Badge Earned!', ?, 'success')");
            $stmtU->bind_param("is", $uid, $uMsg);
            $stmtU->execute();
            
            // 2. Notify All Admins
            $uNameRes = $conn->query("SELECT full_name FROM users WHERE id = $uid");
            $uName = $uNameRes->fetch_assoc()['full_name'];
            
            $aMsg = "User $uName has completed the '$testTitle' assessment.";
            $admins = $conn->query("SELECT id FROM users WHERE role = 'admin'");
            while($adm = $admins->fetch_assoc()) {
                $adminId = $adm['id'];
                $stmtA = $conn->prepare("INSERT INTO notifications (user_id, title, message, type) VALUES (?, 'Skill Test Completed', ?, 'info')");
                $stmtA->bind_param("is", $adminId, $aMsg);
                $stmtA->execute();
            }
            
            echo json_encode(['success' => true, 'test_completed' => true]);
        } else {
            // Just advance
            $conn->query("UPDATE user_skill_progress SET current_stage = $nextStage WHERE user_id = $uid AND test_id = $tid");
            echo json_encode(['success' => true, 'test_completed' => false]);
        }
    } else {
        // Mismatch, maybe re-playing old stage? Just success.
        echo json_encode(['success' => true]);
    }
    exit;
}


function analyzeSentimentAI($text) {
    if (!defined('GEMINI_API_KEY') || empty(GEMINI_API_KEY)) return analyzeSentiment($text);

    $url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" . GEMINI_API_KEY;
    
    // Sanitize text for JSON
    $cleanText = str_replace('"', '\"', $text);
    $prompt = "Analyze the sentiment of this report from a citizen: \"$cleanText\". Respond with ONLY one word from these options: positive, neutral, negative.";
               
    $data = [
        "contents" => [["parts" => [["text" => $prompt]]]]
    ];
    
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_TIMEOUT, 5);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($httpCode === 200) {
        $result = json_decode($response, true);
        $sentiment = strtolower(trim($result['candidates'][0]['content']['parts'][0]['text'] ?? ''));
        if (strpos($sentiment, 'positive') !== false) return 'positive';
        if (strpos($sentiment, 'negative') !== false) return 'negative';
        if (strpos($sentiment, 'neutral') !== false) return 'neutral';
    }
    
    return analyzeSentiment($text); // Fallback to keyword analysis
}

function analyzeSentiment($text) {
    $text = strtolower($text);
    $negative_words = ['broken', 'bad', 'fail', 'dirty', 'dangerous', 'delay', 'poor', 'crime', 'noise', 'garbage', 'flood', 'leak', 'slow', 'problem', 'complaint', 'worst', 'hate', 'trash', 'smell', 'dark', 'error', 'broken'];
    $positive_words = ['great', 'good', 'fast', 'helpful', 'clean', 'safe', 'thanks', 'excellent', 'effective', 'improve', 'benefit', 'love', 'best', 'satisfied', 'resolved', 'perfect'];
    
    $score = 0;
    foreach($positive_words as $w) {
        if(strpos($text, $w) !== false) $score++;
    }
    foreach($negative_words as $w) {
        if(strpos($text, $w) !== false) $score--;
    }
    
    if($score > 0) return 'positive';
    if($score < 0) return 'negative';
    return 'neutral';
}



if ($action === 'get_announcements') {
    $announcements = [];
    $res = $conn->query("SELECT * FROM announcements ORDER BY created_at DESC");
    if($res) {
        while($row = $res->fetch_assoc()) $announcements[] = $row;
    }
    echo json_encode($announcements);
    exit;
}

if ($action === 'create_announcement') {
    $title = $_POST['title'] ?? '';
    $cat = $_POST['category'] ?? '';
    $content = $_POST['content'] ?? '';
    $imagePath = '';

    // Auto-Heal: Ensure table exists and ID is AUTO_INCREMENT
    $conn->query("CREATE TABLE IF NOT EXISTS announcements (
        id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        category VARCHAR(100) NOT NULL,
        content TEXT NOT NULL,
        image_path VARCHAR(255) DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");
    
    // Attempt to set AUTO_INCREMENT just in case it exists but is broken
    $conn->query("ALTER TABLE announcements MODIFY id INT(11) NOT NULL AUTO_INCREMENT");

    if (isset($_FILES['image']) && $_FILES['image']['error'] == 0) {
        $target_dir = "uploads/announcements/";
        if (!file_exists($target_dir)) {
            if (!mkdir($target_dir, 0755, true)) {
                echo json_encode(['error' => 'Failed to create upload directory']);
                exit;
            }
        }
        
        $fileExt = strtolower(pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION));
        $allowed = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
        if(!in_array($fileExt, $allowed)) {
             echo json_encode(['error' => 'Invalid file type']);
             exit;
        }

        $fileName = time() . "_" . uniqid() . "." . $fileExt;
        $target_file = $target_dir . $fileName;
        
        if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
            $imagePath = $target_file;
        } else {
            echo json_encode(['error' => 'Failed to move uploaded file']);
            exit;
        }
    }

    $stmt = $conn->prepare("INSERT INTO announcements (title, category, content, image_path) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("ssss", $title, $cat, $content, $imagePath);
    
    if ($stmt->execute()) {
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

if ($action === 'delete_announcement') {
    $input = json_decode(file_get_contents('php://input'), true);
    $id = $input['id'];
    
    // Get image path to delete file
    $res = $conn->query("SELECT image_path FROM announcements WHERE id = $id");
    if ($row = $res->fetch_assoc()) {
        if (!empty($row['image_path']) && file_exists($row['image_path'])) {
            unlink($row['image_path']);
        }
    }
    
    $stmt = $conn->prepare("DELETE FROM announcements WHERE id = ?");
    $stmt->bind_param("i", $id);
    if ($stmt->execute()) {
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['error' => $conn->error]);
    }
    exit;
}

if ($action === 'get_intelligence_data') {
    if($role !== 'admin') {
         echo json_encode(['error' => 'Unauthorized']); exit;
    }
    
    $insights = [
        'sentiment' => ['positive' => 0, 'neutral' => 0, 'negative' => 0],
        'trends' => [],
        'prediction' => 0,
        'urgent_issues' => []
    ];

    // Schema Patch: Add sentiment column if missing
    $conn->query("ALTER TABLE reports ADD COLUMN IF NOT EXISTS sentiment VARCHAR(20) DEFAULT NULL");
    
    // 1. NLP: Analyze Citizen Reports (Most recent 100)
    $res = $conn->query("SELECT * FROM reports ORDER BY id DESC LIMIT 100");
    if($res) {
        $ai_count = 0;
        while($row = $res->fetch_assoc()) {
            $desc = $row['description'] ?? $row['message'] ?? '';
            $title = $row['title'] ?? 'Report #' . $row['id'];
            $rid = $row['id'];
            
            if(!$desc) continue;
            
            $sentiment = $row['sentiment'];
            
            // Real-time AI analysis for reports without sentiment (limit to 5 per request to keep it fast)
            if (empty($sentiment) && $ai_count < 5) {
                $sentiment = analyzeSentimentAI($desc);
                if ($sentiment) {
                    $conn->query("UPDATE reports SET sentiment = '$sentiment' WHERE id = $rid");
                    $ai_count++;
                }
            }
            
            // Final fallback if AI failed or skipped
            if (empty($sentiment)) $sentiment = 'neutral';
            
            $insights['sentiment'][$sentiment]++;
            
            if(count($insights['urgent_issues']) < 5) {
                // Formatting
                $excerpt = strlen($desc) > 50 ? substr($desc, 0, 50).'...' : $desc;
                $insights['urgent_issues'][] = [
                    'text' => $excerpt,
                    'sentiment' => $sentiment,
                    'title' => $title
                ];
            }
        }
    }
    
    // 2. ML: Trend Analysis
    // Try using created_at. If it fails, we return empty trends.
    $rawTrends = [];
    $dataPoints = [];
    
    // Check if created_at exists, if not try 'date' or 'timestamp'
    // Actually, just try the query.
    $resTrend = $conn->query("
        SELECT DATE_FORMAT(created_at, '%Y-%m') as m, COUNT(*) as c 
        FROM reports 
        GROUP BY m 
        ORDER BY m ASC
        LIMIT 12
    ");
    
    if($resTrend) {
        while($row = $resTrend->fetch_assoc()) {
            $rawTrends[$row['m']] = (int)$row['c'];
        }
    }
    
    // Fill last 6 months
    for($i = 5; $i >= 0; $i--) {
        $m = date('Y-m', strtotime("-$i months"));
        $count = $rawTrends[$m] ?? 0;
        $insights['trends'][] = ['month' => $m, 'count' => $count];
        $dataPoints[] = $count;
    }
    
    // Prediction Logic
    $count = count($dataPoints);
    if($count >= 2) {
        $totalGrowth = 0;
        $growthPoints = 0;
        for($i = 1; $i < $count; $i++) {
            if($dataPoints[$i-1] > 0) {
              $growth = ($dataPoints[$i] - $dataPoints[$i-1]) / $dataPoints[$i-1];
              $totalGrowth += $growth;
              $growthPoints++;
            }
        }
        $avgGrowth = $growthPoints > 0 ? $totalGrowth / $growthPoints : 0;
        
        $next_val = $dataPoints[$count-1] * (1 + $avgGrowth);
        $insights['prediction'] = round($next_val);
    } else {
        $insights['prediction'] = $dataPoints[$count-1] ?? 0;
    }
    
    // Fallback prediction if 0 but data exists
    if($insights['prediction'] == 0 && array_sum($dataPoints) > 0) $insights['prediction'] = 1;

    echo json_encode($insights);
    exit;
}

if ($action === 'get_maintenance') {
    $maint = [];
    $sql = "SELECT ms.*, u.full_name, u.reference_id as user_ref 
            FROM maintenance_schedules ms 
            LEFT JOIN users u ON ms.user_id = u.id 
            ORDER BY ms.scheduled_date ASC";
    $res = $conn->query($sql);
    if($res) {
        while($row = $res->fetch_assoc()) {
            $maint[] = $row;
        }
    }
    echo json_encode($maint);
    exit;
}

if ($action === 'sync_maintenance') {
    // 1. Detect maintenance from reports
    $detector = [
        'Plumbing/Water' => ['leak', 'tubig', 'faucet', 'toilet', 'flush', 'water'],
        'Electrical' => ['kuryente', 'light', 'outage', 'wire', 'koryente', 'electricity', 'ilaw'],
        'Infrastructure' => ['road', 'bridge', 'pavement', 'crack', 'building', 'wall', 'daan', 'tulay'],
        'Sanitation' => ['garbage', 'trash', 'waste', 'basura', 'drain', 'canal', 'kanal']
    ];
    
    $allKeywords = [];
    foreach($detector as $cat => $kws) $allKeywords = array_merge($allKeywords, $kws);
    
    $whereClause = [];
    foreach($allKeywords as $k) $whereClause[] = "title LIKE '%$k%' OR description LIKE '%$k%'";
    $whereStr = implode(' OR ', $whereClause);
    
    $reports = $conn->query("SELECT * FROM reports WHERE status = 'pending' AND ($whereStr)");
    $syncedCount = 0;
    
    if($reports) {
        while($r = $reports->fetch_assoc()) {
            $maint_id = 'CIMM-' . str_pad($r['id'], 4, '0', STR_PAD_LEFT);
            
            // Check if already exists
            $exists = $conn->query("SELECT id FROM maintenance_schedules WHERE maint_id = '$maint_id'");
            if($exists->num_rows == 0) {
                $facility = $r['title']; // Use report title as facility/location
                
                // Determine type
                $type = 'General Maintenance';
                $combinedText = strtolower($r['title'] . ' ' . $r['description']);
                foreach($detector as $cat => $kws) {
                    foreach($kws as $kw) {
                        if(strpos($combinedText, $kw) !== false) {
                            $type = $cat;
                            break 2;
                        }
                    }
                }

                $date = date('Y-m-d H:i:s', strtotime('+2 days')); // Schedule for soon
                $uid_val = $r['user_id'] ? $r['user_id'] : 'NULL';
                
                // Priority based on certain words
                $priority = 'Medium';
                if(strpos($combinedText, 'urgent') !== false || strpos($combinedText, 'danger') !== false || strpos($combinedText, 'bahid') !== false) {
                    $priority = 'High';
                }

                $sql = "INSERT INTO maintenance_schedules (maint_id, facility, maint_type, scheduled_date, duration, priority, status, user_id) 
                        VALUES (?, ?, ?, ?, 'TBD', ?, 'Scheduled', $uid_val)";
                $stmt = $conn->prepare($sql);
                $stmt->bind_param("sssss", $maint_id, $facility, $type, $date, $priority);
                if($stmt->execute()) $syncedCount++;
            }
        }
    }
    
    echo json_encode(['success' => true, 'synced_count' => $syncedCount]);
    exit;
}

if ($action === 'get_analytics') {
    $data = [
        'summary' => [
            'total_this_month' => 0,
            'approval_rate' => 0,
            'utilization' => '0%', // Resolution Rate
            'total_users' => 0,
            'available_facilities' => 3, // Logic categories
            'total_all_time' => 0,
            'avg_per_user' => 0
        ],
        'status_breakdown' => [
            'approved' => 0, 'pending' => 0, 'rejected' => 0, 'cancelled' => 0
        ],
        'trends' => [
            'labels' => [],
            'data' => []
        ],
        'top_facilities' => [ // Top Issues
            'labels' => [],
            'data' => []
        ],
        'facility_utilization' => [], // Report Categories Breakdown
        'outcomes' => [],
        'sentiments' => [
            'positive' => 0, 'neutral' => 0, 'negative' => 0
        ]
    ];

    // Schema Patch: Check correct timestamp column
    $tsCol = 'created_at';
    $checkTS = $conn->query("SHOW COLUMNS FROM reports LIKE 'submitted_at'");
    if($checkTS && $checkTS->num_rows > 0) $tsCol = 'submitted_at';

    // 1. Basic Stats
    $totalUsers = $conn->query("SELECT COUNT(*) as c FROM users WHERE role = 'user'")->fetch_assoc()['c'];
    $data['summary']['total_users'] = $totalUsers;
    
    $totalAllTime = $conn->query("SELECT COUNT(*) as c FROM reports")->fetch_assoc()['c'];
    $data['summary']['total_all_time'] = $totalAllTime;
    
    if($totalUsers > 0) $data['summary']['avg_per_user'] = round($totalAllTime / $totalUsers, 1);

    // 2. This Month Stats
    $thisMonth = date('Y-m');
    $resThisMonth = $conn->query("SELECT COUNT(*) as c FROM reports WHERE $tsCol LIKE '$thisMonth%'");
    $data['summary']['total_this_month'] = $resThisMonth->fetch_assoc()['c'];

    $resApproved = $conn->query("SELECT COUNT(*) as c FROM reports WHERE $tsCol LIKE '$thisMonth%' AND status = 'approved'");
    $approvedThisMonth = $resApproved->fetch_assoc()['c'];
    
    $resRejected = $conn->query("SELECT COUNT(*) as c FROM reports WHERE $tsCol LIKE '$thisMonth%' AND (status = 'rejected' OR status = 'denied')");
    $rejectedThisMonth = $resRejected->fetch_assoc()['c'];

    if($data['summary']['total_this_month'] > 0) {
        $data['summary']['approval_rate'] = round(($approvedThisMonth / $data['summary']['total_this_month']) * 100, 1);
        $resolutionRate = round((($approvedThisMonth + $rejectedThisMonth) / $data['summary']['total_this_month']) * 100, 1);
        $data['summary']['utilization'] = $resolutionRate . '%';
    }

    // 3. Status Breakdown (This Month)
    $resStatus = $conn->query("SELECT status, COUNT(*) as c FROM reports WHERE $tsCol LIKE '$thisMonth%' GROUP BY status");
    while($row = $resStatus->fetch_assoc()) {
        $data['status_breakdown'][strtolower($row['status'])] = (int)$row['c'];
    }

    // 4. Trends (Last 6 Months)
    for($i = 5; $i >= 0; $i--) {
        $m = date('Y-m', strtotime("-$i months"));
        $label = date('M Y', strtotime("-$i months"));
        $data['trends']['labels'][] = $label;
        $count = $conn->query("SELECT COUNT(*) as c FROM reports WHERE $tsCol LIKE '$m%'")->fetch_assoc()['c'];
        $data['trends']['data'][] = (int)$count;
    }

    // 5. Categorization Logic (Virtual Categories)
    $categories = [
        'Infrastructure' => ['road', 'bridge', 'light', 'water', 'pipe', 'leak', 'broken'],
        'Security' => ['police', 'crime', 'theft', 'fight', 'noise', 'curfew', 'safe'],
        'Health & Sanitation' => ['garbage', 'trash', 'flood', 'drain', 'clinic', 'covid', 'health'],
        'Public Service' => ['permit', 'request', 'assistance', 'form', 'help']
    ];
    
    $catCounts = ['Infrastructure' => 0, 'Security' => 0, 'Health & Sanitation' => 0, 'Public Service' => 0, 'General' => 0];
    
    $resCats = $conn->query("SELECT title FROM reports");
    while($row = $resCats->fetch_assoc()) {
        $t = strtolower($row['title']);
        $matched = false;
        foreach($categories as $cat => $keywords) {
            foreach($keywords as $k) {
                if(strpos($t, $k) !== false) {
                    $catCounts[$cat]++;
                    $matched = true;
                    break 2;
                }
            }
        }
        if(!$matched) $catCounts['General']++;
    }

    // 6. Top Issues (Labels)
    arsort($catCounts);
    $top5 = array_slice($catCounts, 0, 5);
    foreach($top5 as $cat => $count) {
        $data['top_facilities']['labels'][] = $cat;
        $data['top_facilities']['data'][] = $count;
    }

    // 7. Category Utilization (Resolution status within categories for this month)
    foreach($catCounts as $cat => $count) {
        if($count > 0) {
            $perc = round(($count / $totalAllTime) * 100, 1);
            $data['facility_utilization'][] = ['name' => $cat, 'count' => $count, 'percentage' => $perc];
        }
    }

    // 8. Outcomes Table (Global Total)
    $resOut = $conn->query("SELECT status, COUNT(*) as c FROM reports GROUP BY status");
    $allRes = [];
    while($row = $resOut->fetch_assoc()) $allRes[$row['status']] = $row['c'];
    $totalGlobal = array_sum($allRes);

    // 9. Sentiment Breakdown
    $checkSent = $conn->query("SHOW COLUMNS FROM reports LIKE 'sentiment'");
    if($checkSent && $checkSent->num_rows > 0) {
        $resSent = $conn->query("SELECT sentiment, COUNT(*) as c FROM reports GROUP BY sentiment");
        while($row = $resSent->fetch_assoc()) {
            $s = strtolower($row['sentiment'] ?? 'neutral');
            if(isset($data['sentiments'][$s])) $data['sentiments'][$s] = (int)$row['c'];
        }
    }
    
    foreach(['approved', 'pending', 'rejected'] as $s) {
        $count = $allRes[$s] ?? 0;
        $share = $totalGlobal > 0 ? round(($count / $totalGlobal) * 100, 1) : 0;
        $data['outcomes'][] = ['status' => ucfirst($s), 'count' => $count, 'share' => $share];
    }

    echo json_encode($data);
    exit;
}

echo json_encode(['error' => 'Invalid action']);
exit;

