<?php
session_start();
include 'db_connect.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

$appId = $_GET['app_id'] ?? 0;
// Fetch details
$sql = "SELECT pa.*, p.title, p.description, u.full_name FROM program_applications pa 
        JOIN programs p ON pa.program_id = p.id 
        JOIN users u ON pa.user_id = u.id
        WHERE pa.id = $appId";
$res = $conn->query($sql);
if(!$res || $res->num_rows == 0) die("Material not found.");
$data = $res->fetch_assoc();

// Simulate PDF View
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Material - <?php echo $data['title']; ?></title>
    <style>
        body { background: #525659; margin: 0; display: flex; justify-content: center; height: 100vh; font-family: sans-serif; }
        .page { background: white; width: 210mm; height: 297mm; margin: 2rem; padding: 2rem; box-shadow: 0 0 10px rgba(0,0,0,0.5); position: relative; }
        h1 { color: #333; text-align: center; margin-top: 3rem; text-transform: uppercase; letter-spacing: 2px; }
        .content { margin-top: 4rem; line-height: 1.6; color: #444; }
        .cert-footer { position: absolute; bottom: 3rem; width: 100%; text-align: center; color: #777; font-size: 0.8rem; }
        .stamp { position: absolute; bottom: 5rem; right: 4rem; width: 100px; height: 100px; border: 3px solid #d32f2f; border-radius: 50%; color: #d32f2f; display: flex; align-items: center; justify-content: center; font-weight: bold; transform: rotate(-15deg); opacity: 0.8; font-size: 1.2rem; }
        @media print { body { background: white; } .page { margin: 0; box-shadow: none; } }
    </style>
</head>
<body>
    <div class="page">
        <div style="text-align:center; margin-bottom:2rem;">
            <div style="font-size:1.5rem; font-weight:bold; color:#1e293b;">LGU3 LIVELIHOOD PROGRAM</div>
            <div style="color:#64748b;">Official Learning Module</div>
        </div>
        <hr style="border:0; border-top:2px solid #333;">
        
        <h1><?php echo $data['title']; ?></h1>
        
        <div class="content">
            <p><strong>Prepared for:</strong> <?php echo $data['full_name']; ?></p>
            <p><strong>Date Issued:</strong> <?php echo date('F j, Y'); ?></p>
            <br>
            <h3>Module Overview</h3>
            <p><?php echo $data['description']; ?></p>
            <p>This document certifies that the above individual has been accepted into the Livelihood Program. Please present this document at the Barangay Hall for scheduled training sessions.</p>
            <br>
            <h3>Next Steps</h3>
            <ol>
                <li>Print this document.</li>
                <li>Attend the orientation at the LGU Center.</li>
                <li>Complete the practical assessment.</li>
            </ol>
        </div>
        
        <div class="stamp">OFFICIAL<br>LGU3</div>
        
        <div class="cert-footer">
            Generated by Main Livelihood System with AI Analysis<br>
            Document ID: <?php echo md5($data['id']); ?>
        </div>
    </div>
    <script>
        window.print();
    </script>
</body>
</html>
